language: php

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - >
    if [ "$TYPO3" == "dev-master" ]; then
      composer config minimum-stability dev;
      composer require typo3/cms-backend="dev-master" --no-update;
      composer require typo3/cms-core="dev-master" --no-update;
    fi
  - composer require nimut/typo3-complete="$TYPO3"
  - mkdir -p .Build/Web/typo3conf/ext/
  - if [ ! -L .Build/Web/typo3conf/ext/content_defender ]; then ln -snvf ../../../../. .Build/Web/typo3conf/ext/content_defender; fi
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running functional tests";
    echo;
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}';

  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;

jobs:
  fast_finish: true
  allow_failures:
    - env: TYPO3=dev-master
    - env: Static code analysis
  include:
    - stage: test
      php: 7.2
      env: TYPO3=dev-master
    - stage: test
      php: 7.2
      env: TYPO3=^9.0
    - stage: test
      php: 7.2
      env: TYPO3=^8.0
    - stage: test
      php: 7.1
      env: TYPO3=^8.0
    - stage: test
      php: 7.0
      env: TYPO3=^8.0

    - &phpstan
      stage: test
      php: 7.2
      env: Static code analysis
      before_script: skip
      script:
        - travis_fold start before_phpstan
        - travis_time_start
        - echo
        - echo "Running php static analysis"
        - echo
        - echo
        - composer require phpstan/phpstan=^0.9 --update-with-dependencie
        - travis_time_finish
        - travis_fold end before_phpstan
        - .Build/bin/phpstan analyse -c .phpstan.neon --level 5 Classes Tests-
    - <<: *phpstan
      php: 7.1
    - <<: *phpstan
      php: 7.0
