dist: bionic

language: php

addons:
    apt:
        packages:
            - parallel
    sonarcloud:
        organization: "ichhabrecht-github"

cache:
    directories:
        - $HOME/.config/composer/cache
        - $HOME/.sonar/cache

jdk:
    - oraclejdk8

services:
    - mysql

jobs:
    fast_finish: true
    allow_failures:
        -   env: TYPO3=dev-main
        -   env: TYPO3=~12.0.0
        -   if: type != cron
            env: TYPO3=11.5.x-dev
        -   if: type != cron
            env: TYPO3=10.4.x-dev
    include:
        - &tests
            stage: ðŸƒ tests
            before_install:
                - if php -i | grep -v TRAVIS_CMD | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
            install:
                - composer require --no-progress --no-suggest --no-update typo3/cms-core:"$TYPO3"
                - composer update
                - git checkout composer.json
            before_script:
                - mkdir -p .Build/public/typo3conf/ext/
                - if [ ! -L .Build/public/typo3conf/ext/content_defender ]; then ln -snvf ../../../../. .Build/public/typo3conf/ext/content_defender; fi
                - export TYPO3_PATH_ROOT=$PWD/.Build/public
                - export typo3DatabaseName=typo3
                - export typo3DatabaseHost=localhost
                - export typo3DatabaseUsername=root
                - export typo3DatabasePassword=
            script:
                - >
                    if [ -d "Tests/Unit" ]; then
                        echo;
                        echo "Running unit tests";
                        echo;
                        echo;
                        .Build/bin/phpunit --bootstrap .Build/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php --testsuite unit;
                    fi

                - >
                    if [ -d "Tests/Functional" ]; then
                        echo;
                        echo "Running functional tests";
                        echo;
                        echo;
                        find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --bootstrap .Build/vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTestsBootstrap.php {}';
                    fi

                - >
                    echo;
                    echo "Running php lint";
                    echo;
                    echo;
                    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
            php: 8.1.0
            env: TYPO3=~12.2.0
        -   <<: *tests
            php: 8.1.0
            env: TYPO3=~12.1.0
        -   <<: *tests
            php: 8.1.0
            env: TYPO3=~12.0.0
        -   <<: *tests
            php: 8.1.0
            env: TYPO3=^11.5
        -   <<: *tests
            php: 8.0
            env: TYPO3=^11.5
        -   <<: *tests
            php: 7.4
            env: TYPO3=^11.5
        -   <<: *tests
            php: 7.4
            env: TYPO3=^10.4

        -   stage: ðŸš¢ to ter
            if: tag IS present AND env(TYPO3_ORG_USERNAME) IS present AND env(TYPO3_ORG_PASSWORD) IS present
            php: 7.4
            before_install:
                - sudo sed 's/mozilla.DST_Root_CA_X3.crt/!mozilla\/DST_Root_CA_X3.crt/' -i /etc/ca-certificates.conf
                - sudo update-ca-certificates
            script:
                - >
                    echo;
                    echo "Preparing upload of release ${TRAVIS_TAG} to TER";
                    echo;
                    echo;
                    composer global require typo3/tailor;

                - >
                    TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`;
                    echo;
                    echo "Uploading release ${TRAVIS_TAG} to TER";
                    echo;
                    echo;
                    PATH=$PATH:$(composer global config bin-dir --absolute --quiet);
                    TYPO3_API_USERNAME="$TYPO3_ORG_USERNAME" TYPO3_API_PASSWORD="$TYPO3_ORG_PASSWORD" tailor ter:publish --comment "$TAG_MESSAGE" ${TRAVIS_TAG} content_defender;

        -   stage: âœ” with sonarqube scanner
            if: type = push AND branch IN (main, pre-merge) AND env(SONAR_TOKEN) IS present AND fork = false
            git:
                depth: false
            php: 8.1
            env: TYPO3="^11.5 ~12.0.0 ~12.1.0 ~12.2.0"
            before_install:
                - nvm install 12
                - nvm use 12
            before_script:
                - mkdir -p .Log/coverage/ .Log/junit/
                - export TYPO3_PATH_WEB=$PWD/.Build/public
                - export typo3DatabaseName=typo3
                - export typo3DatabaseHost=localhost
                - export typo3DatabaseUsername=root
                - export typo3DatabasePassword=
            script:
                - >
                    if [ -d "Tests" ]; then
                        for TYPO3 in $TYPO3; do

                            echo;
                            echo "Running TYPO3 version $TYPO3";
                            echo;
                            echo;
                            git clean -Xdf;
                            composer require --dev --no-progress --no-suggest --no-update typo3/cms-core:"$TYPO3";
                            composer update;
                            git checkout composer.json;
                            VERSION=${TYPO3//[!0-9]/};

                            mkdir -p .Build/public/typo3conf/ext/
                            if [ ! -L .Build/public/typo3conf/ext/content_defender ]; then ln -snvf ../../../../. .Build/public/typo3conf/ext/content_defender; fi

                            if [ -d "Tests/Unit" ]; then
                              echo;
                              echo "Running unit tests";
                              echo;
                              echo;
                              .Build/bin/phpunit --bootstrap .Build/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php --log-junit .Log/junit/unit_$VERSION.xml --coverage-php .Log/coverage/unit_$VERSION.cov  --testsuite unit;
                            fi

                            if [ -d "Tests/Functional" ]; then
                              echo;
                              echo "Running functional tests";
                              echo;
                              echo;
                              .Build/bin/phpunit --bootstrap .Build/vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTestsBootstrap.php --log-junit .Log/junit/functional_$VERSION.xml --coverage-php .Log/coverage/functional_$VERSION.cov --testsuite functional;
                            fi
                        done

                        echo;
                        echo "Merging log and coverage files";
                        echo;
                        echo;
                        composer require --no-progress --no-suggest --no-update nimut/phpunit-merger;
                        composer update;
                        .Build/bin/phpunit-merger coverage .Log/coverage/ .Log/coverage.xml;
                        .Build/bin/phpunit-merger log .Log/junit/ .Log/junit.xml;
                    fi

                - >
                    echo;
                    echo "Running SonarQube Scanner";
                    echo;
                    echo;
                    sonar-scanner;

        - &dev-tests
            <<: *tests
            stage: ðŸƒ dev tests
            before_install:
                - if php -i | grep -v TRAVIS_CMD | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
                - composer config minimum-stability dev
                - composer config prefer-stable true
                - composer require --no-progress --no-suggest --no-update typo3/minimal:"@dev"
                - composer require --no-progress --no-suggest --no-update typo3/cms-core:"@dev"
                - composer require --no-progress --no-suggest --no-update typo3/cms-backend:"@dev"
                - composer require --no-progress --no-suggest --no-update typo3/cms-fluid-styled-content:"@dev"
                - composer require --no-progress --no-suggest --no-update typo3/cms-indexed-search:"@dev"
                - composer require --no-progress --no-suggest --no-update typo3/cms-workspaces:"@dev"
            php: 8.1.0
            env: TYPO3=dev-main
        -   <<: *dev-tests
            php: 8.1.0
            env: TYPO3=11.5.x-dev
        -   <<: *dev-tests
            php: 8.0
            env: TYPO3=11.5.x-dev
        -   <<: *dev-tests
            php: 7.4
            env: TYPO3=11.5.x-dev
        -   <<: *dev-tests
            php: 7.4
            env: TYPO3=10.4.x-dev

        - &lowest-tests
            <<: *dev-tests
            stage: ðŸƒ prefer-lowest tests
            if: type = cron
            install:
                - composer require --no-progress --no-suggest --no-update typo3/cms-composer-installers:"^1.5 || ^2.0"
                - composer require --no-progress --no-suggest --no-update --prefer-lowest typo3/cms-core:"$TYPO3"
                - composer update
                - git checkout composer.json
            php: 8.1.0
            env: TYPO3=dev-main
        -   <<: *lowest-tests
            php: 8.1.0
            env: TYPO3=^12.0
        -   <<: *lowest-tests
            php: 8.1.0
            env: TYPO3=^11.5
        -   <<: *lowest-tests
            php: 8.1.0
            env: TYPO3=11.5.x-dev
        -   <<: *lowest-tests
            php: 8.0
            env: TYPO3=^11.5
        -   <<: *lowest-tests
            php: 8.0
            env: TYPO3=11.5.x-dev
        -   <<: *lowest-tests
            php: 7.4
            env: TYPO3=^11.5
        -   <<: *lowest-tests
            php: 7.4
            env: TYPO3=11.5.x-dev
        -   <<: *lowest-tests
            php: 7.4
            env: TYPO3=^10.4
        -   <<: *lowest-tests
            php: 7.4
            env: TYPO3=10.4.x-dev
